In [1]:
"""
A PyTorch Tensor is conceptually identical to a numpy array: a Tensor 
is an n-dimensional array, and PyTorch provides many functions for 
operating on these Tensors. Behind the scenes, Tensors can keep track 
of a computational graph and gradients, but they’re also useful as 
a generic tool for scientific computing.
"""
import torch

# Create 1D tensor
a = torch.tensor([1,3,5])
print(a)

# Scalar multiplication 
b = a * 3
print(b)

# Tensors multiplication
a = torch.tensor([1,2])
b = torch.tensor([2,3])
c = a * b
print(c)

# Tensor shape
print("Tensor size:", c.size())
print("Tensor size:", c.shape)
print("Tensor max:", torch.max(c))

tensor([1, 3, 5])
tensor([ 3,  9, 15])
tensor([2, 6])
Tensor size: torch.Size([2])
Tensor size: torch.Size([2])
Tensor max: tensor(6)
